### ISSUE TITLE
Swal is not defined

### ISSUE THREAD

**Issue by imran300** [akhled/livewire-sweetalert#1]
Hello,
I have followed your configuration settings and it says swal is not defined..
![Capture](https://user-images.githubusercontent.com/7050400/113395240-fb080280-93b2-11eb-995e-0b9b995858c8.PNG)

**Comment by amrography** [comment]
That issue is because Sweetalert script is missing. You either include it from CDN `<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>` or install it with npm and require it into your laravel-mix build

[Sweetalert installation](https://sweetalert.js.org/guides/)
